apiVersion: v2
name: kuard
description: An example Helm chart for kuard application
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: ingress-nginx
    version: ">=4.0.13, <5.0.0"
    repository: https://kubernetes.github.io/ingress-nginx
    condition: nginx.enabled
