apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-admin
  labels:
    app: boot-admin
spec:
  template:
    metadata:
      name: boot-admin
      labels:
        app: boot-admin
    spec:
      containers:
        - image: xpinjection.com/boot-admin:0.1.0
          name: boot-admin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: boot-admin-config
            - secretRef:
                name: boot-admin-auth-credentials
          env:
            - name: actuator.password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: actuator-credentials
            - name: actuator.username
              valueFrom:
                secretKeyRef:
                  key: username
                  name: actuator-credentials
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"
          startupProbe:
            httpGet:
              path: /admin/health/liveness
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /admin/health/liveness
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /admin/health/readiness
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
      restartPolicy: Always
  selector:
    matchLabels:
      app: boot-admin