kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: boot-admin-discoverer-binding
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: boot-admin-discoverer
  apiGroup: ""