apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  template:
    spec:
      containers:
        - name: kuard
          env:
            - name: PARAM
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: my.config.param
