apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
namePrefix: prod-
bases:
  - ../../base
patchesStrategicMerge:
  - configuration.yml
  - scaling.yml
configMapGenerator:
  - name: config
    files:
    - config.properties
