apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuard-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kuard-prod
  project: default
  source:
    helm:
      releaseName: kuard
      valueFiles:
        - values.yaml
      values: |
        ingress:
          host: localhost
    path: k8s/kuard
    repoURL: https://github.com/nazar-art/k8s-examples.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true